version: "3.8"

services:
  web:
    build: .
    command: gunicorn prism_gallery.wsgi:application --bind 0.0.0.0:8004 --workers 1
    volumes:
      - .:/usr/src/prism_gallery/
    ports:
      - 8004:8004
    env_file:
      - ./.env
    depends_on:
      - db2
  db2:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_prism:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5433:5433
volumes:
  postgres_data_prism:
